Repository mdn/workflows, pull requests merged in 2022-05, with the labels that each got.

#35 Allow for passing in arguments to `npm publish` in publish-release
  .github/workflows/publish-release.yml
  README.md
Labels: community

#34 Make idle-issues workflow customizable
  .github/workflows/idle-issues.yml
  README.md
Labels: enhancement, community

#37 Update readme for idle-issues
  README.md
Labels: community

#40 fix:yml - the yaml for publish release was invalid
  .github/workflows/publish-release.yml
Labels: bug

#43 fix: make npm token optional for publish release
  .github/workflows/publish-release.yml
  README.md
Labels: bug

#38 Add the lock-closed workflow
  .github/workflows/lock-closed.yml
  README.md
Labels: enhancement, community

#45 fix: update condition for publish-release
  .github/workflows/publish-release.yml
Labels: 🧰 chore

#51 feat: add label manager workflow
  .github/workflows/set-default-labels.yml
  README.md
Labels: enhancement

#55 fix: only run on target repo
  .github/workflows/auto-merge.yml
  .github/workflows/idle.yml
  .github/workflows/lock-closed.yml
  .github/workflows/new-issues.yml
  .github/workflows/pr-rebase-needed.yml
  .github/workflows/publish-release.yml
  .github/workflows/set-default-labels.yml
  README.md
Labels: documentation, enhancement

#60 fix: idle workflow should not close
  .github/workflows/idle.yml
Labels: bug

#58 feat: add json-lint and markdown-lint as reusable workflows
  .github/workflows/json-lint.yml
  .github/workflows/markdown-lint.yml
  README.md
Labels: documentation, enhancement

#61 docs: update docs for idle action
  README.md
Labels: documentation

#65 bug: fix new issues workflow
  .github/workflows/new-issues.yml
Labels: bug
