Repository mdn/workflows, pull requests merged in 2022-04, with the labels that each got.

#29 chore:automation ~ add auto-merge action
  .github/workflows/auto-merge-workflows.yml
Labels: 🧰 chore

#32 feat: make npm publishing in release please action conditional
  .github/workflows/publish-release.yml
  README.md
Labels: enhancement

#33 Create action for "rebase needed" autolabeler
  .github/workflows/pr-rebase-needed.yml
  README.md
Labels: enhancement, community
